# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
env: 
  matrix:
    - DESTINATION="name=iPhone 6,OS=10.3"
    - DESTINATION="name=iPhone 6,OS=9.3"
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild test -workspace Example/WallabagKit.xcworkspace -scheme WallabagKit-Example -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
